### ISSUE TITLE
0 command.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#48]
No error in the console and when I write /kit view, /advancedkits use, /akit view, etc, this say : Unknown Command, please type /help.

**Comment by benjaminforras** [comment]
Any errors? Please add more details. (Server type, version etc.)

For me it's working.
![image](https://cloud.githubusercontent.com/assets/10364896/26124033/4f578592-3a7d-11e7-851a-54c150639d72.png)

**Comment by TheIntelloBox** [comment]
Nop 0 error : [05:02:02] [Server thread/INFO]: [AdvancedKits] Starting AdvancedKitsReloaded 1.1.9
[05:02:02] [Server thread/INFO]: [ReflectionHelper] Version is v1_11_R1 (11101)
[05:02:02] [Server thread/INFO]: [AdvancedKits] Hooking to Vault.
[05:02:02] [Server thread/INFO]: [AdvancedKits] Loading configuration.
[05:02:02] [Server thread/INFO]: [AdvancedKits] Locale: "en" | Locale file: messages_en.properties
[05:02:02] [Server thread/INFO]: [AdvancedKits] Loading KitManager.
[05:02:02] [Server thread/INFO]: [AdvancedKits] Loaded 61 kit(s).
[05:02:02] [Server thread/INFO]: [AdvancedKits] Registering events
[05:02:02] [Server thread/INFO]: [AdvancedKits] Registering commands.
[05:02:02] [Server thread/INFO]: [AdvancedKits] Checking for updates.
[05:02:02] [Server thread/INFO]: [AdvancedKits] Finished loading AdvancedKitsReloaded 1.1.9 by TryHardDood

I'm on Spigot 1.11.2 using Java 8.

**Comment by benjaminforras** [comment]
Can you send me the plugins list?

**Comment by aikar** [comment]
Issue is resolved, please recompile @TryHardDood with latest ACF (still 0.4.0)

**Comment by TryHardDood** [comment]
@aikar The problem still exists. (With the latest ACF)
![image](https://cloud.githubusercontent.com/assets/10364896/26213209/7fafde70-3bf8-11e7-9dd9-af70df2c0758.png)

**Comment by benjaminforras** [comment]
@aikar Thanks.
@TheIntelloBox Please download v1.1.9 again it should work.

**Comment by TheIntelloBox** [comment]
I already downloaded this version. :) You can't post it again on GitHub in 1.2.0 please ? :) Thanks my friend ! :)

**Comment by benjaminforras** [comment]
I updated the file this is why I'm asking you to redownload it.
